version: "3.8"
services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx-portainer-templates
        volumes:
            - ./templates.json:/usr/share/nginx/html/templates.json
        ports:
            - 8888:80
        deploy:
            resources:
                limits:
                    cpus: 0.50
                    memory: 512M
                reservations:
                    cpus: 0.25
                    memory: 128M
        restart: unless-stopped